---
groups:
- name: default
  jobs:
  - unit-tests
  - e2e-tests

jobs:
- name: unit-tests
  plan:
  - get: knctl
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          version: trusty
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -e -x -u
          apt-get -y update
          apt-get -y install wget curl

          wget -O- https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz > /tmp/go
          echo "fa1b0e45d3b647c252f51f5e1204aba049cde4af177ef9f2181f43004f901035  /tmp/go" | sha256sum -c
          tar -C /usr/local -xzf /tmp/go
          export PATH=$PATH:/usr/local/go/bin

          export GOPATH=$PWD/gopath
          cd $GOPATH/src/github.com/cppforlife/knctl

          ./hack/build.sh
          ./hack/test.sh
      inputs:
      - name: knctl
        path: gopath/src/github.com/cppforlife/knctl

- name: e2e-tests
  plan:
  - get: knctl
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          version: xenial
      params:
        KUBECONFIG_CONTENTS: ((kubeconfig))
        DOCKER_USERNAME: ((docker_username))
        DOCKER_PASSWORD: ((docker_password))
        KNCTL_E2E_BUILD_GIT_URL: https://github.com/cppforlife/simple-app
        KNCTL_E2E_BUILD_GIT_REVISION: master
        KNCTL_E2E_BUILD_IMAGE: docker.io/dkalinin/test-push:latest
        KNCTL_E2E_BUILD_GIT_REVISION_V1: v1
        KNCTL_E2E_BUILD_GIT_REVISION_V2: v2
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -e -x -u
          apt-get -y update
          apt-get -y install wget curl gnupg

          apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
          touch /etc/apt/sources.list.d/kubernetes.list 
          echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
          apt-get -y update
          apt-get -y install kubectl

          wget -O- https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz > /tmp/go
          echo "fa1b0e45d3b647c252f51f5e1204aba049cde4af177ef9f2181f43004f901035  /tmp/go" | sha256sum -c
          tar -C /usr/local -xzf /tmp/go
          export PATH=$PATH:/usr/local/go/bin

          mkdir -p ~/.kube
          set +x
          echo "$KUBECONFIG_CONTENTS" > ~/.kube/config
          set -x

          export GOPATH=$PWD/gopath
          cd $GOPATH/src/github.com/cppforlife/knctl

          ./hack/build.sh
          ln -s $PWD/knctl /usr/local/bin/knctl

          export KNCTL_NAMESPACE=$(date +%s%N | sha256sum | cut -f1 -d' ' | head -c 32)
          knctl create namespace

          function finish {
            kubectl delete ns $KNCTL_NAMESPACE
          }
          trap finish EXIT

          set +x
          knctl create basic-auth-secret -s registry1 --docker-hub -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          knctl create service-account -a acct1 -s registry1
          set -x
          export KNCTL_E2E_NAMESPACE=$KNCTL_NAMESPACE
          export KNCTL_E2E_BUILD_SERVICE_ACCOUNT=acct1

          ./hack/test-e2e.sh 
      inputs:
      - name: knctl
        path: gopath/src/github.com/cppforlife/knctl

resources:
- name: knctl
  type: git
  source:
    uri: https://github.com/cppforlife/knctl
    branch: master
